import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ColorModeScript } from "@yamada-ui/react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "~/components/common/header";
import { ConvexClientProvider, UIProvider } from "~/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable}`}
          suppressHydrationWarning
        >
          <ColorModeScript initialColorMode="dark" />
          <ConvexClientProvider>
            <UIProvider>
              <Header />
              {children}
            </UIProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
